[package]
name = "xgpu"
version = "0.0.1-alpha.0"
description = "A wrapper for gpu graphics / compute APIs"
authors = ["Jacob R. Green"]
edition = "2021"
license-file = "LICENSE"

[features]
default = ["validation", "graphics", "vulkan"]
validation = []
graphics = []
compute = []
vulkan = ["dep:vulkan-sys"]
directx = ["windows/Win32_UI_WindowsAndMessaging", "windows/Win32_Graphics_Dxgi", "windows/Win32_Graphics_Dxgi_Common", "windows/Win32_Graphics_Direct3D", "windows/Win32_Graphics_Direct3D12"]

[dependencies]
log = { version = "0.4.21" }
thiserror = "1.0.30"
bitflags = "2.5.0"

vulkan-sys = { path = "../vulkan-sys", optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = ["Win32"] }

[dev-dependencies]
glfw = "0.55.0"
env_logger = "0.11.3"

